replicaCount: 3
sources:
  - service
  - ingress

serviceTypeFilter:
  - LoadBalancer

triggerLoopOnEvent: true
interval: "1m"
policy: sync
registry: "txt"
txtOwnerId: "rke2"
txtPrefix: "rke2"

provider: pdns
pdns:
  apiUrl: "http://ns1.chmurka"
  apiPort: "8081"
  apiKey: "8wcjznux0bj8ljarlsfauc9tlr0cthis"

manageRecordTypeFilters:
  - A

extraArgs:
  txt-wildcard-replacement: wildcard
  pdns-skip-tls-verify: ""

logFormat: json
logLevel: info

metrics:
  enabled: true
